// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnzgnnrpneyoonwvveno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuemdubnJwbmV5b29ud3Z2ZW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzgwODMsImV4cCI6MjA2NzYxNDA4M30.FubrYCXOP37nv-UDYAlCh031r8VSzjdJMRvq5GRWqV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});